name: Check
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu-2210
          - fedora-37
          - fedora-37-nightly
          - fedora-38
          - debian-bookworm
          - debian-bookworm-lts
    steps:
    - uses: actions/checkout@v2

    - name: Check (clang-format, build, btest, clang-tidy)
      run: docker build -t zeekjs-check-${{ matrix.distro }} -f docker/${{ matrix.distro }}.Dockerfile .
